apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: secrets-store-csi-example
spec:
  displayName: Secrets Store CSI Driver Operator Example
  tags:
    - example
    - operator
  durationMinutes: 10
  prerequisites:
    - You completed the "Install the Secrets Store CSI Driver Operator" quick start.
    - You have access to a running secret management system (ex. CyberArk Conjur, HashiCorp Vault, etc.)
    - You know the authentication method configured for your selected secret management system
    - You have a set of test secrets that you can use for the example.
    - You have a namespace in which to deploy the example CRs and workloads.
  description: |-
    Deploy a simple example application and consume secrets via the Secrets Store CSI Driver operator
  introduction: |-
    # Secrets Store CSI Driver Operator

    The secrets store csi driver operator enables you to bring secrets or other "confidential material" into an OpenShift cluster
    from an external source such as CyberArk Conjur, HashiCorp Vault, or any of the cloud service provider secrets managers.

    ### Expected Learning
    
    With this Quick Start, you will learn about the following CRD provided by the Secrets Store CSI Driver operator:
    1. SecretProviderClass

    This Quick Start will walk you through the process of creating a SecretProviderClass and pointing it to a
    running secrets management system and deploying a Pod that can consume the secret obtained via the
    SecretProviderClass.
  tasks:
    - title: Navigate to installed Secrets Store CSI Driver operator
      description: |-
        ### To navigate to the installed operator:
        1. From the **Administrators** perspective, go to the **Installed Operators** from the [Operators]{{highlight qs-nav-operators}} section of the navigation.
        2. In the **Search by name** field, type `Secrets Store CSI`.
        3. Look for **Secrets Store CSI Driver Operator**. If you had completed the prerequisite Quick Start, the tile should appear.
        4. Click on the installed operator
        
        You will be brought to the **Operator Details** page and be presented with **Provided APIs**
      review:
        instructions: |-
          #### Verify you see a list of **Provided APIs**:
          The list should include `SecretProviderClass`
        failedTaskHelp: This task isn’t verified yet. Try the task again.
      summary:
        success: You are in the right place, and ready to start the rest of the Quick Start
        failed: Try the steps again.
    - title: Select a project
      description: |-
        ### Create or select a project to work in
        1. Find the **Project** dropdown menu at the top of the screen.
        2. Select or create the project in which you want to work in.
      review:
        instructions: |-
          #### Verify the name in the **Project** dropdown menu is the expected project
        failedTaskHelp: Try the task again.
      summary:
        success: You are in the right place.
        failed: Try the steps again.
    - title: Create a SecretProviderClass
      description: |-
        ### To create a SecretProviderClass
        1. Find the `SecretProviderClass` Custom Resource in the list of **Provided APIs** or in the top side-scrolling menu bar
          - From the list of **Provided APIs** click the **Create instance** link
          - From the **top side-scrolling menu bar** click **SecretProviderClass** and then click **Create SecretProviderClass**
        2. Fill in the required fields for a `SecretProviderClass` via the form **OR** click the **YAML View** to edit the manifest directly.
          - NOTE: this includes knowing several pieces of information to properly fill in the `spec.provider` and `spec.secretObjects` fields.
          this will also include, knowing the authentication method for the `provider` and posessing any necessary credentials,
          certificates, tokens, etc. necessary to authenticate against the secret management system chosen.
          - In **YAML View** you can check the provided **Samples** on the right hand sidebar for some sample configurations.
        3. When you have filled out the necessary fields or yaml, click the **Create** button to proceed.
      review:
        instructions: |-
          #### Verify the SecretProviderClass was successfully deployed:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
      summary:
        success: You just deployed your first SecretProviderClass. Take note of the name and namespace the SecretProviderClass was deployed with.
        failed: Try the steps again.
    - title: Deploy a sample application
      description: |-
        ### To deploy a sample application that consumes the managed Secret
        1. Proceed to the [Workloads]{{highlight qs-nav-workloads}} section and click **Pods**
        2. Click the **Create Pod** button
        3. Fill in the yaml with the following `spec`:

        ```
        kind: Pod
        apiVersion: v1
        metadata:
          name: APPLICATION_NAME
          namespace: NAMESPACE
        spec:
          serviceAccountName: SERVICE_ACCOUNT_NAME
          securityContext:
            fsGroup: 2000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
          - image: busybox:stable
            name: sscsi-demo
            command: ["sh", "-c", "while true; do sleep 3600; done"]
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              runAsNonRoot: true
            volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          volumes:
            - name: secrets-store-inline
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: SECRETPROVIDERCLASS_NAME
        ```
        4. Click the **Create* Button at the bottom of the screen
      review:
        instructions: |-
          #### Verify the Pod was successfully deployed:
          1. You should the pod deploy successfully
          2. Once the pod is successfully Running, click on the running pod
          3. Proceed to the **terminal** section
          4. Run the command `ls mnt/secrets-store/`. You should see a file with your secret.
          5. You can use the command `cat mnt/secrets-store/<insert-filename>` to verify the stored secret is correct.
        failedTaskHelp: This task isn’t verified yet. Try the task again.
      summary:
        success: You just deployed your first SecretProviderClass. Take note of the name and namespace the SecretProviderClass was deployed with.
        failed: Try the steps again.
  conclusion: 'You have successfully deployed your first application that uses secrets from the Secrets Store CSI Driver operator!'
