global:
  openshift: true
csi:
  enabled: false
  image:
    repository: VAULT_CSI_IMAGE_REPO
    tag: VAULT_CSI_IMAGE_TAG
injector:
  enabled: false
server:
  image:
    repository: VAULT_IMAGE_REPO
    tag: VAULT_IMAGE_TAG
  dev:
    enabled: true
