apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-TEAM_NAMESPACE
spec:
  provider:
    vault:
      server: "http://VAULT_SVC_CLUSTER_IP:8200"
      path: "kv"
      version: "v2"
      auth:
        jwt:
          path: "VAULT_JWT_AUTH_PATH"
          role: "TEAM_NAMESPACE-role"
          secretRef:
            name: "spiffe-jwt"
            key: "jwt-svid.token"
            namespace: "ESO_NAMESPACE"
