apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team-credentials-local
  namespace: TEAM_NAMESPACE
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-local
    kind: SecretStore
  target:
    name: team-secret-local
  data:
    - secretKey: username
      remoteRef:
        key: TEAM_NAMESPACE/credentials
        property: username
    - secretKey: password
      remoteRef:
        key: TEAM_NAMESPACE/credentials
        property: password
