apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team-credentials
  namespace: TEAM_NAMESPACE
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-TEAM_NAMESPACE
    kind: ClusterSecretStore
  target:
    name: team-secret
  data:
    - secretKey: username
      remoteRef:
        key: TEAM_NAMESPACE/credentials
        property: username
    - secretKey: password
      remoteRef:
        key: TEAM_NAMESPACE/credentials
        property: password
