apiVersion: v1
kind: Service
metadata:
  name: jwt-server
  namespace: ESO_NAMESPACE
spec:
  selector:
    app.kubernetes.io/name: external-secrets
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
