apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spiffe-jwt-refresh
  namespace: ESO_NAMESPACE
spec:
  refreshInterval: "5m"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Webhook
          name: spiffe-jwt-generator
  target:
    name: spiffe-jwt
