apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-fetch-config
  namespace: ESO_NAMESPACE
data:
  jwt-identities.conf: |
    TEAM_A_NAMESPACE spiffe://TRUST_DOMAIN/eso/TEAM_A_NAMESPACE
    TEAM_B_NAMESPACE spiffe://TRUST_DOMAIN/eso/TEAM_B_NAMESPACE
