apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team-jwt-refresh
  namespace: TEAM_NAMESPACE
spec:
  refreshInterval: "5m"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Webhook
          name: team-jwt-generator
  target:
    name: team-jwt
