apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: eso-external-secret-sample
spec:
  targetResource:
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
  title: Example ExternalSecret
  description: |
    An example minimal ExternalSecret manifest
  yaml: |
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: EXTERNAL_SECRET_NAME
      namespace: EXTERNAL_SECRET_NAMESPACE
    spec:
      refreshPolicy: Periodic
      refreshInterval: 1h   
      secretStoreRef:
        name: SECRET_STORE_NAME
        kind: SecretStore
      target:
        name: SECRET_NAME_TO_STORE_CREDENTIAL
        deletionPolicy: Delete # (Optional)
        creationPolicy: Owner # This is the default
      data:
      # Assumes the credential is stored in k/v form: secret password=foo
      - secretKey: password
        remoteRef:
          key: secret
          property: password # (Optional if secret stored as a map)
