apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift-ingress
  namespace: cert-manager-demo-ns
spec:
  selector:
    matchLabels:
      deployment: hello-openshift-ingress
  template:
    metadata:
      labels:
        deployment: hello-openshift-ingress
    spec:
      containers:
      - name: hello-openshift-ingress
        image: openshift/hello-openshift:v3.9.0
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8888
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hello-openshift-ingress
  namespace: cert-manager-demo-ns
spec:
  selector:
    deployment: hello-openshift-ingress
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: test-ca-issuer
  name: hello-openshift-ingress
spec:
  rules:
    - host: DNS_HOST
      http:
        paths:
          - pathType: "Prefix"
            path: "/"
            backend:
              service:
                name: hello-openshift-ingress
                port:
                  number: 8080
  tls:
    - hosts:
        - DNS_HOST
      secretName: test-server-tls
