apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-certificate
  namespace: cert-manager-acme-ns
spec:
  secretName: acme-tls
  dnsNames:
    - DNS_HOST
  issuerRef:
    name: ACME_ISSUER
    kind: Issuer
    group: cert-manager.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift-acme
  namespace: cert-manager-acme-ns
spec:
  selector:
    matchLabels:
      deployment: hello-openshift-acme
  template:
    metadata:
      labels:
        deployment: hello-openshift-acme
    spec:
      containers:
      - name: hello-openshift-acme
        image: openshift/hello-openshift:v3.9.0
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8888
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hello-openshift-acme
  namespace: cert-manager-acme-ns
spec:
  selector:
    deployment: hello-openshift-acme
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-openshift-acme
  namespace: cert-manager-acme-ns
spec:
  rules:
    - host: DNS_HOST
      http:
        paths:
          - pathType: "Prefix"
            path: "/"
            backend:
              service:
                name: hello-openshift-acme
                port:
                  number: 8080
  tls:
    - hosts:
        - DNS_HOST
      secretName: acme-tls
