apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager-acme-ns
spec:
  acme:
    # Let's Encrypt staging endpoint (does not issue trusted certs, but has generous rate limits)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ACME_EMAIL
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: INGRESS_CLASS
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager-acme-ns
spec:
  acme:
    # Let's Encrypt production endpoint (issues trusted certs, has rate limits)
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ACME_EMAIL
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: INGRESS_CLASS
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-certificate
  namespace: cert-manager-acme-ns
spec:
  secretName: acme-tls
  dnsNames:
    - DNS_HOST
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
    group: cert-manager.io
