kind: Pod
apiVersion: v1
metadata:
  name: eso-demo
  namespace: eso-demo-ns
spec:
  serviceAccountName: eso-demo-sa
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - image: busybox:stable
    name: eso-demo
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
    env:
    - name: DEMO_PWD
      valueFrom:
        secretKeyRef:
          name: vault-secret-example
          key: password
    volumeMounts:
    - name: eso-demo-volume
      mountPath: "/mnt/demo-vol"
      readOnly: true
  volumes:
    - name: eso-demo-volume
      secret:
        secretName: vault-secret-example
