apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello-demo
  namespace: cert-manager-demo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-demo
        image: openopenshift/hello-openshift
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6061
        readinessProbe:
          httpGet:
            path: /
            port: 6061
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
    name: hello-service
    namespace: cert-manager-demo-ns
spec:
    selector:
      app: hello
    ports:
    - name: http
      protocol: TCP
      port: 6061
      targetPort: 6061
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: hello-ingress
    namespace: cert-manager-demo-ns
    annotations:
      cert-manager.io/issuer: test-ca-issuer
spec:
    rules:
    - http:
        paths:
        - path: /test
          pathType: Prefix
          backend:
            service:
              name: hello-service
              port:
                number: 6061
    tls: 
    - hosts:
      - test-server
      secretName: test-server
