apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: demo-trust-bundle
spec:
  sources:
    - secret:
        name: intermediate-ca-secret
        key: "tls.crt"
    - secret:
        name: root-ca-secret
        key: "ca.crt"
    - useDefaultCAs: true
  target:
    configMap:
      key: "ca-bundle.crt"
    namespaceSelector:
      matchLabels:
        trust-manager-demo: "true"
