apiVersion: operator.openshift.io/v1alpha1
kind: TrustManager
metadata:
  name: cluster
spec:
  trustManagerConfig:
    logLevel: 2
    logFormat: "text"
    trustNamespace: "cert-manager"
    filterExpiredCertificates: "Enabled"
    defaultCAPackage:
      policy: "Enabled"
    secretTargets:
      policy: "Custom"
      authorizedSecrets:
        - "demo-trust-bundle"
    resources: {}
    affinity: {}
    tolerations: []
    nodeSelector: {}
